# Generated by Django 5.1.5 on 2025-01-21 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
