# Generated by Django 5.1.5 on 2025-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_class_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('p', 'publish'), ('d', 'draft')], default='p', max_length=1),
        ),
    ]
