# Generated by Django 5.1.5 on 2025-01-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_remove_class_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
