# Generated by Django 5.1.4 on 2025-01-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadmaps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='user',
            new_name='creator',
        ),
    ]
