# Generated by Django 5.1.5 on 2025-01-23 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animations', '0004_animation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='status',
        ),
    ]
