# Generated by Django 5.1.5 on 2025-01-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_comment_created_at_alter_course_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('p', 'publish'), ('d', 'draft')], default='p', max_length=1),
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.CharField(choices=[('p', 'publish'), ('d', 'draft')], default='p', max_length=1),
        ),
    ]
